# Generated by Django 5.2.13 on 2026-05-03 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=180)),
                ('asset_type', models.CharField(choices=[('real_estate', 'Real Estate'), ('business_stake', 'Business Stake'), ('stock', 'Stock'), ('fund', 'Fund'), ('gold', 'Gold'), ('cash', 'Cash'), ('crypto', 'Crypto'), ('private_investment', 'Private Investment'), ('other', 'Other')], default='other', max_length=40)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('currency', models.CharField(default='SAR', max_length=8)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ownership_percentage', models.DecimalField(decimal_places=4, default=100, max_digits=7)),
                ('income_generated', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='SAR', max_length=8)),
                ('income_type', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to='investments.asset')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='SAR', max_length=8)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.asset')),
            ],
        ),
    ]
