# Generated by Django 5.2.13 on 2026-05-03 12:13

import apps.accounts.models
import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('project_manager', 'Project Manager'), ('accountant', 'Accountant'), ('partner', 'Partner'), ('investor', 'Investor'), ('viewer', 'Viewer')], default='viewer', max_length=32)),
                ('dashboard_access', models.CharField(choices=[('full', 'Full'), ('partner', 'Partner'), ('financial', 'Financial'), ('readonly', 'Readonly'), ('custom', 'Custom')], default='readonly', max_length=20)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=80, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=apps.accounts.models.default_invitation_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('preferred_language', models.CharField(default='ar', max_length=10)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('project_manager', 'Project Manager'), ('accountant', 'Accountant'), ('partner', 'Partner'), ('investor', 'Investor'), ('viewer', 'Viewer')], default='viewer', max_length=32)),
                ('dashboard_access', models.CharField(choices=[('full', 'Full'), ('partner', 'Partner'), ('financial', 'Financial'), ('readonly', 'Readonly'), ('custom', 'Custom')], default='readonly', max_length=20)),
                ('can_view_dashboard', models.BooleanField(default=True)),
                ('can_view_financials', models.BooleanField(default=False)),
                ('can_view_sensitive_accounts', models.BooleanField(default=False)),
                ('can_view_raw_excel', models.BooleanField(default=False)),
                ('can_upload_excel', models.BooleanField(default=False)),
                ('can_import_data', models.BooleanField(default=False)),
                ('can_add_transactions', models.BooleanField(default=False)),
                ('can_edit_transactions', models.BooleanField(default=False)),
                ('can_delete_transactions', models.BooleanField(default=False)),
                ('can_export_reports', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_view_customers', models.BooleanField(default=False)),
                ('can_view_suppliers', models.BooleanField(default=False)),
                ('can_view_profit', models.BooleanField(default=False)),
                ('can_view_partner_dashboard', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_project_invites', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'project', 'is_active'], name='accounts_pr_user_id_c99e8a_idx')],
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ProjectStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ownership_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('capital_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit_share_percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
