# Generated by Django 5.2.13 on 2026-05-03 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('adset_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=180)),
                ('campaign_id', models.CharField(blank=True, max_length=120)),
                ('objective', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=80)),
                ('account_name', models.CharField(max_length=180)),
                ('account_id', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='SAR', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_accounts', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AdPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('cpa', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('roas', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('roi', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('ctr', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('cpc', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cpm', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_metrics', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('ad_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('adset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='ads.adset')),
            ],
        ),
        migrations.CreateModel(
            name='AdSpendDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('leads', models.PositiveIntegerField(default=0)),
                ('orders', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='SAR', max_length=8)),
                ('source', models.CharField(default='manual', max_length=80)),
                ('ad_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_spend', to='ads.adaccount')),
            ],
        ),
    ]
