# Generated by Django 5.2.8 on 2026-05-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_databasebackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
