# Generated by Django 5.2.13 on 2026-05-02 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly_financial', 'Monthly Financial'), ('project_profit_loss', 'Project Profit/Loss'), ('cash_position', 'Cash Position'), ('ecommerce_performance', 'Ecommerce Performance'), ('real_estate_collections', 'Real Estate Collections'), ('ads_performance', 'Ads Performance'), ('investments', 'Investments'), ('partners', 'Partners'), ('investors', 'Investors')], max_length=60)),
                ('title', models.CharField(max_length=180)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(default='generated', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='projects.project')),
            ],
        ),
    ]
