# Generated by Django 5.2.13 on 2026-05-03 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrialBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('activity', models.CharField(blank=True, max_length=180)),
                ('declared_units', models.PositiveIntegerField(default=0)),
                ('source_sheet', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_buildings', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IndustrialCustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=220)),
                ('contact_person', models.CharField(blank=True, max_length=180)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('activity', models.CharField(blank=True, max_length=180)),
                ('budget', models.CharField(blank=True, max_length=120)),
                ('required_units', models.CharField(blank=True, max_length=220)),
                ('building_name', models.CharField(blank=True, max_length=120)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=180)),
                ('first_contact', models.CharField(blank=True, max_length=80)),
                ('last_contact', models.CharField(blank=True, max_length=80)),
                ('relationship_status', models.CharField(blank=True, max_length=80)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_customer_profiles', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IndustrialReservationLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=220)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('building_name', models.CharField(blank=True, max_length=120)),
                ('unit_number', models.CharField(blank=True, max_length=80)),
                ('area', models.CharField(blank=True, max_length=80)),
                ('activity', models.CharField(blank=True, max_length=180)),
                ('rent_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('next_step', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industrial_reservation_leads', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IndustrialUnitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('unit_number', models.CharField(max_length=80)),
                ('unit_type', models.CharField(blank=True, max_length=80)),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activity', models.CharField(blank=True, max_length=180)),
                ('tenant_name', models.CharField(blank=True, max_length=220)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('national_id_or_cr', models.CharField(blank=True, max_length=100)),
                ('rent_per_meter', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('annual_rent', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('booking_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contract_start', models.DateField(blank=True, null=True)),
                ('contract_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('rented', 'مؤجر'), ('reserved', 'محجوز'), ('vacant', 'غير مؤجر')], default='vacant', max_length=24)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_records', to='real_estate.industrialbuilding')),
            ],
            options={
                'ordering': ['building_id', 'sequence', 'unit_number'],
                'unique_together': {('building', 'unit_number')},
            },
        ),
    ]
