# Generated by Django 5.2.13 on 2026-05-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_industrialbuilding_industrialcustomerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrialcustomerprofile',
            name='next_step',
            field=models.TextField(blank=True),
        ),
    ]
