# Generated by Django 5.2.13 on 2026-05-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_industrialcustomerprofile_next_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrialbuilding',
            name='external_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='industrialbuilding',
            name='external_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='industrialunitrecord',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
