# Generated by Django 5.2.13 on 2026-05-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_industrialbuilding_external_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AddField(
            model_name='tenant',
            name='activity_type',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='tenant',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='external_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenant',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
