# Generated by Django 5.2.8 on 2026-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_customer_addresses_json_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_abandoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocode',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promocode',
            name='number_of_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='promocode',
            name='percentage_off',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='promocode',
            name='promo_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='promocode',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=40),
        ),
        migrations.AddField(
            model_name='promocode',
            name='usage_limit',
            field=models.IntegerField(default=0),
        ),
    ]
